# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: sim_protobuf_messages.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Vector2(betterproto.Message):
    """Shared vector2 representation"""

    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)


@dataclass
class AgentGoal(betterproto.Message):
    """Agent goal assignment"""

    agent_id: int = betterproto.int32_field(1)
    goal: "Vector2" = betterproto.message_field(2)


@dataclass
class AgentState(betterproto.Message):
    """Agent state per step"""

    agent_id: int = betterproto.int32_field(1)
    position: "Vector2" = betterproto.message_field(2)
    velocity: "Vector2" = betterproto.message_field(3)
    preferred_velocity: "Vector2" = betterproto.message_field(4)
    distance_to_goal: float = betterproto.float_field(5)


@dataclass
class AgentInitData(betterproto.Message):
    """Agent initialization data"""

    agent_id: int = betterproto.int32_field(1)
    radius: float = betterproto.float_field(2)
    max_speed: float = betterproto.float_field(3)
    neighbor_dist: float = betterproto.float_field(4)
    max_neighbors: int = betterproto.int32_field(5)
    time_horizon: float = betterproto.float_field(6)
    time_horizon_obst: float = betterproto.float_field(7)
    goal: "Vector2" = betterproto.message_field(8)
    behaviour: str = betterproto.string_field(9)


@dataclass
class Obstacle(betterproto.Message):
    """Obstacles are a list of vertex sequences"""

    vertices: List["Vector2"] = betterproto.message_field(1)


@dataclass
class AllGoalsProcessedMessage(betterproto.Message):
    step: int = betterproto.int32_field(1)
    goals: List["AgentGoal"] = betterproto.message_field(2)


@dataclass
class SimulationInitializedMessage(betterproto.Message):
    step: int = betterproto.int32_field(1)
    agent_initialization_data: List["AgentInitData"] = betterproto.message_field(2)
    obstacles: List["Obstacle"] = betterproto.message_field(3)
    goals: List["AgentGoal"] = betterproto.message_field(4)


@dataclass
class AgentsStateUpdateMessage(betterproto.Message):
    step: int = betterproto.int32_field(1)
    agent_state_list: List["AgentState"] = betterproto.message_field(2)


@dataclass
class ObstaclesProcessedMessage(betterproto.Message):
    step: int = betterproto.int32_field(1)
    obstacles: List["Obstacle"] = betterproto.message_field(2)


@dataclass
class GoalPositionUpdatedMessage(betterproto.Message):
    step: int = betterproto.int32_field(1)
    goals: List["AgentGoal"] = betterproto.message_field(2)


@dataclass
class NewObstacleAddedMessage(betterproto.Message):
    step: int = betterproto.int32_field(1)
    obstacle: "Obstacle" = betterproto.message_field(2)


@dataclass
class RayHit(betterproto.Message):
    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)


@dataclass
class RayCastingUpdateMessage(betterproto.Message):
    step: int = betterproto.int32_field(1)
    agent_id: int = betterproto.int32_field(2)
    hits: List["RayHit"] = betterproto.message_field(3)
